name: Handle Release

on:
  release:
    types: [created]

jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Get zip
      run: |
        zip -r slang /home/runner/work/SlangCompilier/SlangCompilier/SLangCompilier/bin/Release/netcoreapp3.1
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        path: slang.zip
    - name: Attach to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: slang.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
